# Catch-all HTTPS with self-signed cert (returns 404)
server {
    listen ${NGINX_PORT} ssl default_server;
    server_name _;

    ssl_certificate /etc/ssl/certs/selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/selfsigned.key;

    return 404;
}

server {
    listen ${NGINX_PORT} ssl;
    server_name ${DOMAIN_NAME};

    root /var/www/html;
    index index.php index.html index.htm;

    ssl_certificate /etc/ssl/certs/selfsigned.crt;
    ssl_certificate_key /etc/ssl/private/selfsigned.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_prefer_server_ciphers on;
    ssl_ciphers HIGH:!aNULL:!MD5;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass wordpress:${WP_PORT};
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location = /favicon.ico {
        root /var/www/html;
        try_files /favicon.ico =404;
        log_not_found off;
        access_log off;
    }
}
