version : "3.8"

services :
  nginx :
    build : "./requirements/nginx/"
    ports :
      - "443:443"
    environment :
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks :
      - inception-network
    volumes :
      - wordpress:/wordpress

networks:
  inception-network:

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rguigneb/data/wordpress
  DB:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rguigneb/data/DB

