services :
  nginx :
    build : "./requirements/nginx/"
    restart: always
    ports :
      - "443:443"
    environment :
      - DOMAIN_NAME=${DOMAIN_NAME}
    networks :
      - inception-network
    volumes :
      - wordpress:/var/www/html
    depends_on:
      - wordpress

  redis:
    build : "./requirements/bonus/redis/"
    restart: always
    depends_on:
      - wordpress
    networks:
      - inception-network

  adminer:
    build : "./requirements/bonus/adminer/"
    restart: always
    depends_on:
      - mariadb
    networks:
      - inception-network

  static-website:
    build : "./requirements/bonus/static-website/"
    restart: always
    ports:
      - "1313:1313"
    volumes:
      - static-website:/quickstart/
    depends_on:
      - nginx
    networks:
      - inception-network

  wordpress :
    build : "./requirements/wordpress/"
    secrets:
      - db_password
    restart: always
    environment :
      WORDPRESS_DB_HOST: mariadb:3306
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
      WORDPRESS_DB_USER: ${MYSQL_USER}
      DOMAIN_NAME: ${DOMAIN_NAME}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_SUB_USER: ${WP_SUB_USER}
      WP_SUB_EMAIL: ${WP_SUB_EMAIL}
      WP_SUB_PASSWORD: ${WP_SUB_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
    networks :
      - inception-network
    volumes :
      - wordpress:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    build:
      context: "./requirements/mariadb/"
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    secrets:
      - db_password
      - db_root_password
    networks:
      - inception-network
    volumes:
      - mariadb:/var/lib/mysql

# Define secrets
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt


networks:
  inception-network:
    driver: bridge
volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rguigneb/data/wordpress
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rguigneb/data/mariadb
  static-website:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rguigneb/data/static-website

