CREATE DATABASE IF NOT EXISTS ${WP_DATABASE};
CREATE USER IF NOT EXISTS '${WP_USER}'@'%' IDENTIFIED BY '${WP_PASSWORD}';
GRANT ALL PRIVILEGES ON ${WP_DATABASE}.* TO '${WP_USER}'@'%';

FLUSH PRIVILEGES;
