CREATE DATABASE IF NOT EXISTS ${WP_DATABASE};
CREATE USER IF NOT EXISTS '${WP_USER}'@'%' IDENTIFIED BY '${WP_PASSWORD}';
GRANT ALL PRIVILEGES ON ${WP_DATABASE}.* TO '${WP_USER}'@'%';

CREATE DATABASE IF NOT EXISTS ${N8N_DB_NAME};
CREATE USER IF NOT EXISTS '${N8N_DB_USER}'@'%' IDENTIFIED BY '${N8N_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${N8N_DB_NAME}.* TO '${N8N_DB_USER}'@'%';

FLUSH PRIVILEGES;
