CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';

CREATE DATABASE IF NOT EXISTS ${N8N_DB_NAME};
CREATE USER IF NOT EXISTS '${N8N_DB_USER}'@'%' IDENTIFIED BY '${N8N_DB_PASSWORD}';
GRANT ALL PRIVILEGES ON ${N8N_DB_NAME}.* TO '${N8N_DB_USER}'@'%';

FLUSH PRIVILEGES;
