# Configuration de base
ftpd_banner=Bienvenue sur le serveur ftp de LUCAS
listen=YES
listen_port=21
background=NO

# Configuration Docker
seccomp_sandbox=NO

# Utilisateurs
local_enable=YES
anonymous_enable=NO
write_enable=YES

# Chroot
chroot_local_user=YES
allow_writeable_chroot=YES

# Liste d'utilisateurs
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Mode passif
pasv_enable=YES
pasv_min_port=40000
pasv_max_port=40010

# PAM
pam_service_name=vsftpd
check_shell=YES

# SSL désactivé
ssl_enable=NO

# Logging
log_ftp_protocol=YES
xferlog_enable=YES
vsftpd_log_file=/var/log/vsftpd.log
