ftpd_banner=Bienvenue sur le serveur ftp de LUCAS

listen_port=222

anonymous_enable=YES
anon_upload_enable=NO
anon_mkdir_write_enable=NO
anon_other_write_enable=NO
anon_world_readable_only=YES
anon_root=<Path_du_répertoire_anonyme>
