# Configuration de base
ftpd_banner=Server FTP (rguigneb prime)
listen=YES
listen_port=${FTP_PORT}
background=NO

# Utilisateurs
local_enable=YES
anonymous_enable=NO
write_enable=YES

# Chroot
chroot_local_user=YES
allow_writeable_chroot=YES

# Liste d'utilisateurs
userlist_enable=YES
userlist_file=/etc/vsftpd.userlist
userlist_deny=NO

# Mode passif
pasv_enable=YES
pasv_min_port=${FTP_MIN_PORT}
pasv_max_port=${FTP_MAX_PORT}

# SSL
ssl_enable=YES
rsa_cert_file=/etc/ssl/private/vsftpd.pem
rsa_private_key_file=/etc/ssl/private/vsftpd.pem
allow_anon_ssl=NO
ssl_tlsv1=YES
ssl_ciphers=HIGH
